import "@/ui/globals.css";
import Sidebar from "@/ui/sidebar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="container">
          <Sidebar />
          {children}
        </div>
      </body>
    </html>
  );
}
